// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myrcukbpvjotrluvcige.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cmN1a2JwdmpvdHJsdXZjaWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTczMzYsImV4cCI6MjA2MjM5MzMzNn0.A6YxDzVUTLI6Lt2tC0vhxspY9UxXSMcSA1-TMWQyjAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});